### ISSUE TITLE
Publish to MELPA?

### ISSUE THREAD

**Issue by iainbeeston** [eschulte/emacs24-starter-kit#61]
This might be a dumb question, but why not publish the emacs24-starter-kit to melpa? (or another package archive?) Or perhaps each language-specific starter kit as a separate package?

I prefer to install packages (even starter kits) from a package archive rather than using git, because I find it easier to manage.

**Comment by stormwatch** [comment]
So how should I load the starter kit once I install through MELPA instead of git?

For now I've written my own init.el and modified the hook function as follows:
```elisp
;; load the starter kit from the `after-init-hook' so all packages are loaded
(add-hook 'after-init-hook
 `(lambda ()
    ;; remember this directory
    (setq starter-kit-dir
          (package-desc-dir (cadr (assq 'literate-starter-kit package-alist))))
    ;; only load org-mode later if we didn't load it just now
    ,(unless (and (getenv "ORG_HOME")
                  (file-directory-p (expand-file-name "lisp"
                                                      (getenv "ORG_HOME"))))
       '(require 'org))
    ;; load up the starter kit
    (org-babel-load-file (expand-file-name "starter-kit.org" starter-kit-dir))))

;;; init.el ends here
```
It works but I wonder if it is necessary to revert `package-user-dir` to its original value.
