### ISSUE TITLE
Autocompletion?

### ISSUE THREAD

**Issue by gerroon** [eschulte/emacs24-starter-kit#74]
Hi

I just downloaded your package. No need to say that I am an Emacs beginner. One thing that I seem to miss is Autocomplete and not sure how to go ahead with your setup. Do you mind including one or explaining how to add without breaking your package?  

I already did very basic custom stuff with git branching and adding a custom theme.

thanks

**Comment by eschulte** [comment]
If you load starter-kit-misc.org you'll get "M-/" bound to hippie-expand, which I use locally for auto-completion.

**Comment by gerroon** [comment]
thanks
